version: "3.8"

networks:
  proxy:
    external: true
services:
  react-home-assistant:
    container_name: react-home-assistant
    image: app-prod
    ports:
      - "1337:80"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.entrypoints=http"
      - "traefik.http.routers.react.rule=Host(`home-automation.kanoa.be`)"
      - "traefik.http.middlewares.react-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.react.middlewares=react-https-redirect"
      - "traefik.http.routers.react-secure.entrypoints=https"
      - "traefik.http.routers.react-secure.rule=Host(`home-automation.kanoa.be`)"
      - "traefik.http.routers.react-secure.tls=true"
      - "traefik.http.routers.react-secure.tls.certresolver=http"
      - "traefik.http.routers.react-secure.service=react-home-assistant"
      - "traefik.http.services.react.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"